version: '2.1'

# mostly extending from main .yml
services:
  test-e2e:
    build: test/e2e
    restart: "no"
    environment:
    - BOILERPLATE_DOMAIN
    - OIDC_RESPONSE_TYPE
    - OIDC_SCOPE
    - OIDC_CLIENT_ID
    - OIDC_REDIRECT_URI
    - OIDC_AUTHORITY_URL
    - OIDC_TCTOKEN_ID
    - OIDC_SESSION_ID
    - OIDC_REFRESH_ID
    - OIDC_ACCESS_TOKEN
    - OIDC_RESTRICTED_ID
    - OIDC_STATE
    - OIDC_NONCE
    - OIDC_OPENID_PARAMETER
    #- BOILERPLATE_IPV4_16PREFIX
    #- BOILERPLATE_IPV6_ADDRESS
    depends_on:
    - www
    networks:
    - front
