# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('response_type', models.CharField(max_length=30)),
                ('_redirect_uris', models.TextField(default='')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('client_type', models.CharField(default='confidential', max_length=30)),
                ('jwt_alg', models.CharField(default='RS256', max_length=10)),
                ('contact_email', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.CharField(blank=True, default='', max_length=255)),
                ('terms_url', models.CharField(blank=True, default='', max_length=255)),
                ('website_url', models.CharField(blank=True, default='', max_length=255)),
                ('_post_logout_redirect_uris', models.TextField(blank=True, default='')),
            ],
        ),
    ]
