# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcTokenId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sessionId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('refreshId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
